export const AUTHCONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
};

export const USERCONSTANTS = {
  SET_LOADING: 'SET_LOADING',
  SET_DASHBOARD: 'SET_DASHBOARD',
  SET_CONTRIBUTIONS: 'SET_CONTRIBUTIONS',
  SET_LOCATIONS: 'SET_LOCATIONS',
  SET_ACC_BAL: 'SET_ACC_BAL',
  SET_OFFICER: 'SET_OFFICER',
  SET_MISSING: 'SET_MISSING',
};
